project:
  type: website
  resources: 
    - resume.pdf

website:
  title: "GyeongMin Kwon"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: work_experiences.qmd
      - href: project.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



